include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # UI-only phase: silence noisy lints/deprecations
    deprecated_member_use: ignore
    deprecated_member_use_from_same_package: ignore
    unnecessary_import: ignore
    curly_braces_in_flow_control_structures: ignore
    unnecessary_type_check: ignore
    unnecessary_underscores: ignore
    prefer_final_fields: ignore
    unused_local_variable: ignore
    unnecessary_brace_in_string_interps: ignore
    use_build_context_synchronously: ignore
